# These are supported funding model platforms

github: [uwussimo, katsuki-yuri]
patreon: rshehroz1
open_collective: rshehroz1
ko_fi: shehroz
tidelift: great-bits/npm
community_bridge: great-bits
liberapay: rshehroz1
issuehunt: rshehroz1
otechie: shehroz
lfx_crowdfunding: great-bits
custom: ["https://shehroz-blog.vercel.app/", "https://doston.me/"]
